kind: Pod
apiVersion: v1
metadata:
  name: dind
spec:
  containers:
    - name: dind
      image: docker:20.10-dind
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-cache
          mountPath: /var/lib/docker
          subPath: docker-cache
  restartPolicy: Never
  volumes:
    - name: docker-cache
      persistentVolumeClaim:
        claimName: dind-azurefile-pvc
