apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-xfs
  volumeName: azurefile
  resources:
    requests:
      storage: 5Gi
