allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-xfs
mountOptions:
  - dir_mode=0640
  - file_mode=0640
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuName: Standard_LRS
  fsType: ext4
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
